"""fixed typo update_at -> updated_at

Revision ID: 91f99946d5a9
Revises: 0a24907925c5
Create Date: 2026-06-13 00:18:35.332824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91f99946d5a9'
down_revision: Union[str, Sequence[str], None] = '0a24907925c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('blogs', 'update_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('blogs', 'updated_at')
    # ### end Alembic commands ###
