"""added username in the User model

Revision ID: bac5e28d0aad
Revises: 1b3d646e116e
Create Date: 2026-06-13 01:37:47.040123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bac5e28d0aad'
down_revision: Union[str, Sequence[str], None] = '1b3d646e116e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_users_user_name'), 'users', ['user_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_name'), table_name='users')
    op.drop_column('users', 'user_name')
    # ### end Alembic commands ###
